//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRIPCO.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        public int ExpedienteID { get; set; }
        public Nullable<int> CitaID { get; set; }
        public string Comentario { get; set; }
        public string Documento { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Cita Cita { get; set; }
    }
}
