//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRIPCO.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaEspecialidad
    {
        public int PersonaEspecialidadID { get; set; }
        public Nullable<int> PersonaID { get; set; }
        public Nullable<int> EspecialidadID { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
